# This is workflow to publish rwebsite on github pages
name: PH #自动化的名称
on:
  push: # push的时候触发
    branches: # 那些分支需要触发
      - master
jobs:
  build:
    runs-on: ubuntu-20.04 # 镜像市场
    steps:
      - name: checkout # 步骤的名称
        uses: actions/checkout@v2 #软件市场的名称
        with: # 参数
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          extended: true
      - name: Build
        run: hugo -b https://flashsherlock.github.io --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: flashsherlock/flashsherlock.github.io
          publish_branch: master
          publish_dir: ./public
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        with:
          source-repo: "git@github.com:flashsherlock/flashsherlock.github.io.git"
          destination-repo: "git@gitee.com:flashsherlock/flashsherlock.git"